apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-2020-exercise1-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-2020-exercise1
  template:
    metadata:
      labels:
        app: dwk-2020-exercise1
    spec:
      containers:
      - name: dwk-2020-exercise1
        image: shomarov/dwk-2020-exercise1:latest
